---
- name: Create udapeople backend directory
  file:
    state: directory
    path: /opt/udapeople-backend
    owner: ubuntu
    group: ubuntu

- name: Deploy udapeople backend
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /opt/udapeople-backend
    owner: ubuntu
    group: ubuntu

- name: Launch udapeople backend
  shell: |
    cd /opt/udapeople-backend
    npm install
    pm2 stop default
    pm2 start npm -- start
